project_id = "isjflmyhbvdlmcsaewbq"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://idclub.hasky.top"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.course-content]
verify_jwt = false

[functions.course-cover]
verify_jwt = false
